#
# makefile for charley tree editor
#

#list of source files
SRC=dup_link.c addcnrec.c addlink.c addnode.c addrtlnk.c addrtrec.c addtraff.c charinit.c charley.c chkargs.c cntlinks.c conreccd.c contivit.c copylink.c copynet.c cost.c cpyrlink.c delay.c delcnrec.c dellinks.c delnodes.c delrtlks.c delrtrec.c deltraff.c dupstr.c evolve.c filename.c findbest.c findnode.c findrrec.c fitness.c inc_buff.c inivalue.c linkcd.c logger.c mate.c mklinks.c mknet.c mknodes.c mkpop.c mktraff.c netcd.c netparcd.c nodecd.c popcd.c prncnrec.c prnlinks.c prnnet.c prnnodes.c prnntpar.c prnpop.c prnrlink.c prnrtrec.c prntraff.c randcost.c randlink.c randmess.c randmsln.c randnode.c randnum.c randsped.c read_ln.c restlink.c restnode.c routecd.c routes.c rtlinkcd.c sellink.c traffcd.c

#list of object files
OBJ=dup_link.o addcnrec.o addlink.o addnode.o addrtlnk.o addrtrec.o addtraff.o charinit.o charley.o chkargs.o cntlinks.o conreccd.o contivit.o copylink.o copynet.o cost.o cpyrlink.o delay.o delcnrec.o dellinks.o delnodes.o delrtlks.o delrtrec.o deltraff.o dupstr.o evolve.o filename.o findbest.o findnode.o findrrec.o fitness.o inc_buff.o inivalue.o linkcd.o logger.o mate.o mklinks.o mknet.o mknodes.o mkpop.o mktraff.o netcd.o netparcd.o nodecd.o popcd.o prncnrec.o prnlinks.o prnnet.o prnnodes.o prnntpar.o prnpop.o prnrlink.o prnrtrec.o prntraff.o randcost.o randlink.o randmess.o randmsln.o randnode.o randnum.o randsped.o read_ln.o restlink.o restnode.o routecd.o routes.o rtlinkcd.o sellink.o traffcd.o

#list of header files
HDR=network.h

#target name
TARGET=charley
#library and include directories
LIBDIR=-L/usr/lib
INCDIR=-I/usr/include

#compiler flags
COMPFLAGS=-o

#libraries
LIBS=-lm

#compiler name
CC=gcc

#compile it
$(TARGET): $(OBJ) $(HDR)
	$(CC) $(COMPFLAGS) $(TARGET) $(OBJ) $(LIBDIR) $(LIBS)

#lint it
lint:
	lint $(SRC) |tee lint.analysis
#clean up the dir
clean:
	rm -f $(OBJ)

#remove cr from the files
cleandos:
	bash rmcr $(SRC)
	bash rmcr $(HDR)


#list of dependancies
.o:.c $(HDR)

